export const dummyResults = [
{cacheId: "ZmbajEPYOiMJ",
displayLink: "www.glasses.com",
formattedUrl: "https://www.glasses.com/",
htmlFormattedUrl: "https://www.<b>glasses</b>.com/",
htmlSnippet: "Starting from $65, <b>Glasses</b>.com is the trusted online store for most popular <br>\neyewear brands - including Ray-Ban, Oakley, Prada. Shop best brands <br>\nprescription&nbsp;...",
htmlTitle: "<b>Glasses</b> &amp; Prescription Sunglasses Online - <b>Glasses</b>.com®",
kind: "customsearch#result",
link: "https://www.glasses.com/",
snippet: "Starting from $65, Glasses.com is the trusted online store for most popular \neyewear brands - including Ray-Ban, Oakley, Prada. Shop best brands \nprescription ...",
title: "Glasses & Prescription Sunglasses Online - Glasses.com®" },
{ cacheId: "oLH0m2tlO0wJ",
displayLink: "www.zennioptical.com",
formattedUrl: "https://www.zennioptical.com/b/u6.95-glasses",
htmlFormattedUrl: "https://www.zennioptical.com/b/u6.95-<b>glasses</b>",
htmlSnippet: "Find our lowest-priced eyeglass frames, including discounted and clearance <br>\nitems, conveniently organized into one easy-to-find location. Shop now &amp; save!",
htmlTitle: "$6.95 Low Price Eyeglasses | Zenni Optical <b>Glasses</b>",
kind: "customsearch#result",
link: "https://www.zennioptical.com/b/u6.95-glasses",
snippet: "Find our lowest-priced eyeglass frames, including discounted and clearance \nitems, conveniently organized into one easy-to-find location. Shop now & save!",
title: "$6.95 Low Price Eyeglasses | Zenni Optical Glasses"},
{ cacheId: "G2ggrSsFPAQJ",
displayLink: "www.warbyparker.com",
formattedUrl: "https://www.warbyparker.com/eyeglasses",
htmlFormattedUrl: "https://www.warbyparker.com/eye<b>glasses</b>",
htmlSnippet: "To this day, we&#39;ve distributed over four million pairs of <b>glasses</b> to people in need. <br>\n... Amy R, ORI love how you give a pair of <b>glasses</b> to someone in need and the&nbsp;...",
htmlTitle: "Eyeglasses | Warby Parker",
kind: "customsearch#result",
link: "https://www.warbyparker.com/eyeglasses",
snippet: "To this day, we've distributed over four million pairs of glasses to people in need. \n... Amy R, ORI love how you give a pair of glasses to someone in need and the ...",
title: "Eyeglasses | Warby Parker"}]